### ISSUE TITLE
windows 10 crash

### ISSUE THREAD

**Issue by qwertyjuju** [Blackfireoff/FireDown#1] opened 2023-05-16 11:27 UTC
hello, I can't download this video: https://www.youtube.com/watch?v=6vlY1vdkPf4 or any video by the way. I'm on windows10. The program crashes when i click on download

**Comment by Blackfireoff** [comment] 2023-05-17 06:42
Everything work. Try to put the URL without any space before and after it. The error look like this : 
![image](https://github.com/leonardoheron/VOD_Downloader/assets/96128400/1ceb6bb7-8133-4285-b783-8808572afe06)

Tell me back if the error persist.

**Comment by Blackfireoff** [comment] 2023-05-17 09:41
It seems that the problem is related to the '--noconsole' option of pyinstaller. 
I'm working on a patch, in the meantime, use the Python version and I'll publish a windows version with console.

**Comment by Blackfireoff** [comment] 2023-05-19 09:03
It is corrected! The v1.0.2 version is released without console!

**Closed as completed by Blackfireoff** 2023-05-19 09:03 UTC
